### ISSUE TITLE
session plugin always opening `cola`

### ISSUE THREAD

**Issue by mwilliammyers** [mwilliammyers/speedcola#3] opened 2015-08-27 19:37 UTC
Obviously this is an issue with the config located at:
`config/plugin/session.vim`
[xolox/vim-session](https://github.com/xolox/vim-session)

**Comment by mwilliammyers** [comment] 2015-08-27 19:39
Maybe the functionality of opening the last file to [mhinz/vim-startify](https://github.com/mhinz/vim-startify) see: #4 
Or is it worth adding a whole new plugin just for that functionality?

**Comment by mwilliammyers** [comment] 2015-09-01 01:23
Maybe we should open [NERDTree](https://github.com/scrooloose/nerdtree/tree/bcf3de4fdffae45fc7c85b6b84a01b37177924aa) if nothing is specified? See [this](https://github.com/scrooloose/nerdtree/tree/bcf3de4fdffae45fc7c85b6b84a01b37177924aa#faq) on how to do that...

Or maybe we should only open [NERDTree](https://github.com/scrooloose/nerdtree/tree/bcf3de4fdffae45fc7c85b6b84a01b37177924aa) if a directory is specified (spf13 does this) I don't know how though...

**Comment by mayor-wren** [comment] 2015-09-01 03:54
The issue is that `session_default_override` is not being set so whatever session is initially defined will be opened. This is fixed in pull request #12.

**Comment by mwilliammyers** [comment] 2015-09-01 04:01
Merged :smile:

**Closed as completed** 2015-09-01 04:01 UTC
Labels: bug, help wanted, TODO
